### ISSUE TITLE
[Enhancement] Geophilic compatibility

### ISSUE THREAD

**Issue by Yum-Muy** [Apollounknowndev/underground-rivers#1]
Saw this from one of Enderverse's video, and I think this is a really cool addition that I didn't know Tectonic had. Possibility for a compat would be greatly appreciated, as I like more vanilla generation, as well as terralith/tectonic being a bit more hard on the cpu. Just thought it'd be cool.

**Comment by Apollounknowndev** [comment]
Already compatible :P

![image](https://github.com/user-attachments/assets/6c44ff24-556a-4e6c-aaa7-aa022ff90435)

**Comment by Yum-Muy** [comment]
FIRE....
